development:
  adapter: postgresql
  database: trello_tracker_development
  host: localhost
  min_messages: WARNING

test:
  adapter: postgresql
  database: trello_tracker_test
  host: localhost
  min_messages: WARNING